model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentInpaintDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0205
    num_timesteps_cond: 1
    log_every_t: 100
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: masked_image
    cond_stage_trainable: false
    image_size: 128
    channels: 3
    concat_mode: true
    monitor: val/loss_simple_ema
    ckpt_path: models/ldm/inpainting_big/model_compvis.ckpt
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 64
        in_channels: 7
        out_channels: 3
        model_channels: 256
        attention_resolutions:
        - 8
        - 4
        - 2
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 3
        - 4
        num_heads: 8
        resblock_updown: true
        use_checkpoint: true
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 3
        n_embed: 8192
        monitor: val/rec_loss
        ddconfig:
          attn_type: none
          double_z: false
          z_channels: 3
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config: __is_first_stage__
data:
  target: main_inpainting.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 5
    wrap: false
    train:
      target: ldm.data.inpainting_dataset.InpaintingTrain
      params:
        csv_file: data/inpainting_fabric/fabric.csv
        data_root: data/inpainting_fabric/custom_inpainting
        size: 512
    validation:
      target: ldm.data.inpainting_dataset.InpaintingValidation
      params:
        csv_file: data/inpainting_fabric/fabric.csv
        data_root: data/inpainting_fabric/custom_inpainting
        size: 512
